version: '2'

services:  
  master:
    build: 
        context: Docker-master
        dockerfile: Dockerfile
    hostname: master
    ports:
      - "8081:8081"
#    network_mode: "host"
    restart: always
  
  slave:
    environment:
      - ACO_MASTER_HOST=127.0.0.1
      - ACO_MASTER_PORT=8081
    build:
      context: Docker-slave
      dockerfile: Dockerfile
    hostname: slave
    network_mode: "host"
    restart: always
